---
build: off
version: '{build}'
shallow_clone: true
clone_depth: 1
environment:
  nodejs_version: '9'
cache:
  - '%LOCALAPPDATA%\Yarn -> appveyor.yml'
  - node_modules -> package.json
install:
  - ps: Install-Product node $env:nodejs_version x64
  # - ps: choco install -y gpg4win-vanilla
  # - gpg --import test/fixtures/gpg.key
  - ps: Install-Product node $env:nodejs_version x64
  - yarn add -D nyc@11 @oclif/nyc-config@0
test_script:
  - .\node_modules\.bin\nyc --nycrc-path node_modules/@oclif/nyc-config/.nycrc yarn test
after_test:
  - .\node_modules\.bin\nyc --nycrc-path node_modules/@oclif/nyc-config/.nycrc report --reporter text-lcov > coverage.lcov
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh

build: off

