---
version: 2
jobs:
  node-latest: &test-build
    docker:
      - image: node:latest
    working_directory: ~/cli
    environment:
      NYC: "yarn exec nyc -- --nycrc-path node_modules/@oclif/nyc-config/.nycrc"
      MOCHA_FILE: "reports/mocha.xml"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v0-yarn-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{checksum "yarn.lock"}}
            - v0-yarn-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-
            - v0-yarn-{{ .Environment.CIRCLE_JOB }}-master
      - run: gpg --import test/fixtures/gpg.key
      - run: yarn add -D nyc@11 @oclif/nyc-config@0 mocha-junit-reporter@1
      - run: |
          mkdir -p reports
          $NYC yarn test --reporter mocha-junit-reporter
          $NYC report --reporter text-lcov > coverage.lcov
          curl -s https://codecov.io/bash | bash
      - save_cache:
          key: v0-yarn-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{checksum "yarn.lock"}}
          paths:
            - ~/cli/node_modules
            - /usr/local/share/.cache/yarn
  node-8:
    <<: *test-build
    docker:
      - image: node:8

workflows:
  version: 2
  test:
    jobs:
      - node-latest
      - node-8
